project_id = "rwrznilwfczmichtfyyo"

[functions.create-order]
verify_jwt = false

[functions.track-order]
verify_jwt = false

[functions.n8n-webhook]
verify_jwt = false

[functions.submit-query]
verify_jwt = false
